-- Meetings — evidence attached to an Order's discussion in a meeting.
--
-- WHAT THIS ADDS
-- --------------
-- During a review an issue is raised, somebody raises a request with Operations
-- on the spot, and the screenshot of that request belongs in the meeting record.
-- Next meeting, management must be able to see exactly what was communicated at
-- the time — not a later recollection of it.
--
--   1. public.meeting_order_evidence — one row per attached image. APPEND-ONLY:
--      no client role can insert, update or delete a row. Rows arrive only from
--      add_meeting_order_evidence(), which proves the file is really stored
--      before it records anything.
--   2. A private `meeting-evidence` bucket (JPG / PNG / WEBP, 10 MB — the BOE
--      stored-attachment ceiling, 05_Business_Rules.md).
--   3. Storage policies: read = can_view_meeting, write = can_edit_meeting on the
--      Order's meeting. NO UPDATE policy, so an image can never be replaced in
--      place. DELETE is limited to the uploader's OWN object that no evidence row
--      references — the cleanup of an upload whose recording failed, and nothing
--      else. Once recorded, an image cannot be removed by any client.
--   4. remove_meeting_order() re-emitted with one more refusal: an Order with
--      evidence attached is part of the record and cannot be removed.
--
-- WHY A NEW BUCKET, NOT meeting-product-images
-- --------------------------------------------
-- That bucket (20260831000000) lets any meeting editor DELETE objects, because
-- the PI import cleans up after itself. Evidence stored there could be erased
-- through a direct Storage call while its row still pointed at it — a silent
-- removal, which is the one thing evidence must not allow. Its 2 MB / no-WEBP
-- limits are also wrong for phone screenshots. Loosening its policies would
-- change a shipped feature; a separate, stricter bucket changes nothing.
--
-- WHY NOT A ROW IN meeting_update_history
-- ---------------------------------------
-- That table's entry_type is a CHECK constraint and its writer is shared by six
-- functions. Evidence is its own fact with its own columns (path, type, size),
-- and the history table is left exactly as it is. The screen merges the two by
-- meeting and time.
--
-- WHAT IS DELIBERATELY NOT BUILT
--   Captions, comments, reactions, replacement, voiding, non-image files, public
--   URLs, thumbnails generated server-side, and any link to the Orders module.
--   `order_number` is snapshotted exactly as meeting_update_history does it.
--
-- ROLLBACK / CORRECTIVE FORWARD
--   Forward-only. Additive: one table, one bucket, three storage policies, two
--   new functions, one function re-emitted with an extra guard. To retire:
--   re-emit remove_meeting_order() from 20260814000000, then drop the storage
--   policies, the functions, the table and (once emptied) the bucket.

-- ═══ 1. The evidence table ═════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.meeting_order_evidence (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- NO ACTION, never CASCADE: nothing may take evidence away as a side effect.
  -- A meeting with orders already cannot be deleted
  -- (meetings_prevent_delete_with_content), and remove_meeting_order() below
  -- refuses an Order that has evidence.
  meeting_id       uuid        NOT NULL REFERENCES public.meetings(id),
  meeting_order_id uuid        NOT NULL REFERENCES public.meeting_orders(id),

  -- Snapshot, as in meeting_update_history: the row names its Order on its own.
  order_number     text        NOT NULL,

  -- Object key in the meeting-evidence bucket: {meeting_order_id}/{uuid}.{ext}.
  -- Generated by the browser, never the user's filename.
  storage_path     text        NOT NULL UNIQUE,
  -- Display name only. Never used to build a path.
  file_name        text        NOT NULL CHECK (btrim(file_name) <> ''),
  -- Read from Storage's own record of the object, not from the caller.
  mime_type        text        NOT NULL CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/webp')),
  size_bytes       bigint      NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 10485760),

  uploaded_by      uuid        NOT NULL REFERENCES public.users(id),
  created_at       timestamptz NOT NULL DEFAULT now(),

  -- The object lives under its own Order's folder, so the storage policies —
  -- which authorize on that folder — always agree with the row.
  CONSTRAINT meeting_order_evidence_path_in_order_folder
    CHECK (split_part(storage_path, '/', 1) = meeting_order_id::text)
);

-- The two reads this table serves are both "evidence for these meeting_order
-- ids, newest first": the board/workspace for the current meeting, and the
-- Order's earlier meetings. One index covers both.
CREATE INDEX IF NOT EXISTS meeting_order_evidence_order_idx
  ON public.meeting_order_evidence (meeting_order_id, created_at DESC);

COMMENT ON TABLE public.meeting_order_evidence IS
  'Append-only images attached to an Order''s discussion in a meeting. No client role holds INSERT, UPDATE, DELETE or TRUNCATE; rows arrive only from add_meeting_order_evidence(), which verifies the object exists in the private meeting-evidence bucket and was uploaded by the caller. Never replaced, never removed.';

-- ═══ 2. Row Level Security ═════════════════════════════════════════════════

ALTER TABLE public.meeting_order_evidence ENABLE ROW LEVEL SECURITY;

-- Readable by whoever can read the meeting — the same rule as every other
-- meeting child table.
DROP POLICY IF EXISTS "meeting_order_evidence_select" ON public.meeting_order_evidence;
CREATE POLICY "meeting_order_evidence_select" ON public.meeting_order_evidence
  FOR SELECT TO authenticated
  USING (public.can_view_meeting(meeting_id, auth.uid()));

-- The parent module gate every meeting table carries (20260905000000).
DROP POLICY IF EXISTS "meeting_order_evidence_module_entry_gate" ON public.meeting_order_evidence;
CREATE POLICY "meeting_order_evidence_module_entry_gate" ON public.meeting_order_evidence
  AS RESTRICTIVE FOR ALL TO authenticated
  USING (public.module_entry_open('meetings'))
  WITH CHECK (public.module_entry_open('meetings'));

-- Privileges, not only the absence of a policy: a write policy added by mistake
-- later still could not write, and TRUNCATE (which no policy governs) cannot
-- erase the record.
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.meeting_order_evidence FROM authenticated, anon;
REVOKE ALL ON public.meeting_order_evidence FROM anon;
GRANT SELECT ON public.meeting_order_evidence TO authenticated;

-- ═══ 3. The private bucket ═════════════════════════════════════════════════
--
-- Limits live AT THE BUCKET so they hold whatever a client believes. 10 MB is
-- the BOE stored-attachment rule; larger images are compressed in the browser
-- first (src/lib/meetings/evidence.ts), and the bucket refuses anything that
-- still is not under it. These three types MUST stay equal to the table CHECK
-- above and to MEETING_EVIDENCE_MIME_TYPES in the browser.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'meeting-evidence',
  'meeting-evidence',
  false,
  10485760,
  ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO UPDATE SET
  public             = excluded.public,
  file_size_limit    = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- ═══ 4. Is this object already recorded as evidence? ═══════════════════════
--
-- SECURITY DEFINER on purpose. The storage DELETE policy asks this, and it must
-- get the TRUE answer: evaluated under the caller's RLS, a person who can no
-- longer read the meeting would see "no row" and could delete an object they
-- uploaded that IS evidence.

CREATE OR REPLACE FUNCTION public.meeting_evidence_path_recorded(p_path text)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.meeting_order_evidence e WHERE e.storage_path = p_path
  );
$$;

REVOKE EXECUTE ON FUNCTION public.meeting_evidence_path_recorded(text) FROM public, anon;
GRANT  EXECUTE ON FUNCTION public.meeting_evidence_path_recorded(text) TO authenticated;

-- ═══ 5. Storage object policies ════════════════════════════════════════════
--
-- The first path segment is the meeting_order id, compared as TEXT (never a
-- uuid cast, so a malformed name fails quietly) — the convention of
-- 20260711000000 and 20260831000000.

DROP POLICY IF EXISTS "meeting_evidence_select" ON storage.objects;
CREATE POLICY "meeting_evidence_select" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'meeting-evidence'
    AND public.module_entry_open('meetings')
    AND EXISTS (
      SELECT 1 FROM public.meeting_orders o
      WHERE o.id::text = split_part(storage.objects.name, '/', 1)
        AND public.can_view_meeting(o.meeting_id, auth.uid())
    )
  );

-- Only a generated key shape is accepted: {uuid}/{uuid}.{jpg|png|webp}. A
-- traversal, a nested folder or a user filename cannot satisfy it.
DROP POLICY IF EXISTS "meeting_evidence_insert" ON storage.objects;
CREATE POLICY "meeting_evidence_insert" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'meeting-evidence'
    AND public.module_entry_open('meetings')
    AND storage.objects.name ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp)$'
    AND EXISTS (
      SELECT 1 FROM public.meeting_orders o
      WHERE o.id::text = split_part(storage.objects.name, '/', 1)
        AND public.can_edit_meeting(o.meeting_id, auth.uid(), false)
    )
  );

-- Cleanup of a failed recording ONLY: the uploader's own object, and only while
-- no evidence row references it. owner_id is Storage's current ownership column
-- and owner its deprecated predecessor; both are checked (20260700000000).
DROP POLICY IF EXISTS "meeting_evidence_delete_unrecorded" ON storage.objects;
CREATE POLICY "meeting_evidence_delete_unrecorded" ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'meeting-evidence'
    AND (storage.objects.owner_id = auth.uid()::text OR storage.objects.owner = auth.uid())
    AND NOT public.meeting_evidence_path_recorded(storage.objects.name)
  );

-- No UPDATE policy. Replacing the bytes behind a recorded image would rewrite
-- what the meeting saw.

-- ═══ 6. Recording an uploaded image ════════════════════════════════════════
--
-- Storage and PostgreSQL cannot share a transaction, so the browser uploads
-- first and then calls this. It records NOTHING unless the object really exists
-- in the bucket, under this Order's folder, uploaded by the caller — so a failed
-- or abandoned upload can never appear as evidence. Type and size are taken from
-- Storage's own metadata, never from the caller.

CREATE OR REPLACE FUNCTION public.add_meeting_order_evidence(
  p_order_id     uuid,
  p_storage_path text,
  p_file_name    text DEFAULT NULL
)
RETURNS public.meeting_order_evidence
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_order public.meeting_orders;
  v_uid   uuid;
  v_path  text := btrim(COALESCE(p_storage_path, ''));
  v_mime  text;
  v_size  bigint;
  v_name  text;
  v_row   public.meeting_order_evidence;
BEGIN
  -- FOR SHARE: serialises with remove_meeting_order(), which locks FOR UPDATE,
  -- so an Order cannot be removed between this check and the insert.
  SELECT * INTO v_order FROM public.meeting_orders WHERE id = p_order_id FOR SHARE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'MEETING_ORDER_MISSING: This order is no longer part of the meeting'
      USING ERRCODE = '42501';
  END IF;

  -- First, before anything is read or written: editor of a live meeting.
  v_uid := public.assert_meeting_editor(v_order.meeting_id);

  IF v_path !~ ('^' || v_order.id::text || '/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp)$') THEN
    RAISE EXCEPTION 'MEETING_EVIDENCE_PATH_INVALID: That image is not stored under this order'
      USING ERRCODE = '42501';
  END IF;

  SELECT o.metadata ->> 'mimetype', NULLIF(o.metadata ->> 'size', '')::bigint
    INTO v_mime, v_size
  FROM storage.objects o
  WHERE o.bucket_id = 'meeting-evidence'
    AND o.name = v_path
    AND (o.owner_id = v_uid::text OR o.owner = v_uid);

  -- One message for "never uploaded" and "uploaded by somebody else": a caller
  -- must not be able to claim, or probe for, another person's object.
  IF NOT FOUND THEN
    RAISE EXCEPTION 'MEETING_EVIDENCE_NOT_STORED: The image did not finish uploading, so nothing was attached'
      USING ERRCODE = 'P0001';
  END IF;

  IF v_mime IS NULL OR v_mime NOT IN ('image/jpeg', 'image/png', 'image/webp') THEN
    RAISE EXCEPTION 'MEETING_EVIDENCE_TYPE_INVALID: Only JPG, PNG or WEBP images can be attached'
      USING ERRCODE = '22023';
  END IF;

  IF v_size IS NULL OR v_size <= 0 OR v_size > 10485760 THEN
    RAISE EXCEPTION 'MEETING_EVIDENCE_TOO_LARGE: Images must be 10 MB or smaller'
      USING ERRCODE = '22023';
  END IF;

  -- Display text only. Control characters and slashes removed, length capped.
  v_name := left(regexp_replace(btrim(COALESCE(p_file_name, '')), '[[:cntrl:]/]', '', 'g'), 120);
  IF btrim(v_name) = '' THEN
    v_name := 'image';
  END IF;

  INSERT INTO public.meeting_order_evidence (
    meeting_id, meeting_order_id, order_number,
    storage_path, file_name, mime_type, size_bytes, uploaded_by
  ) VALUES (
    v_order.meeting_id, v_order.id, v_order.order_number,
    v_path, v_name, v_mime, v_size, v_uid
  )
  RETURNING * INTO v_row;

  RETURN v_row;
EXCEPTION
  WHEN unique_violation THEN
    RAISE EXCEPTION 'MEETING_EVIDENCE_DUPLICATE: That image is already attached'
      USING ERRCODE = '23505';
END;
$$;

REVOKE EXECUTE ON FUNCTION public.add_meeting_order_evidence(uuid, text, text) FROM public, anon;
GRANT  EXECUTE ON FUNCTION public.add_meeting_order_evidence(uuid, text, text) TO authenticated;

-- ═══ 7. Removing an order — one more refusal ═══════════════════════════════
--
-- Identical to 20260814000000 §8c except the evidence check. Same signature, so
-- every caller is unaffected. Without it the foreign key above would still
-- refuse the delete, but with a constraint error no reader could act on.

CREATE OR REPLACE FUNCTION public.remove_meeting_order(p_order_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_order public.meeting_orders;
BEGIN
  SELECT * INTO v_order FROM public.meeting_orders WHERE id = p_order_id FOR UPDATE;
  IF NOT FOUND THEN RETURN; END IF;

  PERFORM public.assert_meeting_editor(v_order.meeting_id);

  IF EXISTS (
    SELECT 1 FROM public.meeting_update_history
    WHERE meeting_order_id = p_order_id
      AND (
        entry_type IN ('order_update', 'item_update', 'task_linked')
        OR btrim(COALESCE(new_update, '')) <> ''
      )
  ) THEN
    RAISE EXCEPTION 'MEETING_ORDER_HAS_HISTORY: "%" already has recorded updates and cannot be removed', v_order.order_number
      USING ERRCODE = '42501';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.meeting_order_items
    WHERE meeting_order_id = p_order_id AND linked_task_id IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'MEETING_ORDER_HAS_TASKS: "%" has tasks created from it and cannot be removed', v_order.order_number
      USING ERRCODE = '42501';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.meeting_order_evidence
    WHERE meeting_order_id = p_order_id
  ) THEN
    RAISE EXCEPTION 'MEETING_ORDER_HAS_EVIDENCE: "%" has evidence attached and cannot be removed', v_order.order_number
      USING ERRCODE = '42501';
  END IF;

  DELETE FROM public.meeting_orders WHERE id = p_order_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.remove_meeting_order(uuid) FROM public, anon;
GRANT  EXECUTE ON FUNCTION public.remove_meeting_order(uuid) TO authenticated;

-- ═══ 8. Assertions ═════════════════════════════════════════════════════════
--
-- Read-only. Each needle is one the named object itself contains.

DO $$
DECLARE
  v_bad text;
BEGIN
  IF NOT (SELECT c.relrowsecurity FROM pg_class c WHERE c.oid = 'public.meeting_order_evidence'::regclass) THEN
    RAISE EXCEPTION 'meeting_order_evidence must have RLS enabled';
  END IF;

  -- Readable, and nothing else: the only permissive policy is SELECT.
  SELECT string_agg(p.polname, ', ') INTO v_bad
  FROM pg_policy p
  WHERE p.polrelid = 'public.meeting_order_evidence'::regclass
    AND p.polpermissive
    AND p.polcmd <> 'r';
  IF v_bad IS NOT NULL THEN
    RAISE EXCEPTION 'meeting_order_evidence has a permissive write policy: %', v_bad;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policy p
    WHERE p.polrelid = 'public.meeting_order_evidence'::regclass
      AND p.polname = 'meeting_order_evidence_module_entry_gate'
      AND NOT p.polpermissive
      AND p.polcmd = '*'
  ) THEN
    RAISE EXCEPTION 'meeting_order_evidence is missing its RESTRICTIVE module entry gate';
  END IF;

  IF has_table_privilege('authenticated', 'public.meeting_order_evidence', 'INSERT')
     OR has_table_privilege('authenticated', 'public.meeting_order_evidence', 'UPDATE')
     OR has_table_privilege('authenticated', 'public.meeting_order_evidence', 'DELETE')
     OR has_table_privilege('authenticated', 'public.meeting_order_evidence', 'TRUNCATE') THEN
    RAISE EXCEPTION 'authenticated still holds a write privilege on meeting_order_evidence';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM storage.buckets
    WHERE id = 'meeting-evidence' AND NOT public AND file_size_limit = 10485760
  ) THEN
    RAISE EXCEPTION 'meeting-evidence bucket must exist, be private and cap objects at 10 MB';
  END IF;

  -- No UPDATE (or ALL) policy on storage.objects may reach this bucket.
  SELECT string_agg(p.polname, ', ') INTO v_bad
  FROM pg_policy p
  WHERE p.polrelid = 'storage.objects'::regclass
    AND p.polcmd IN ('w', '*')
    AND (COALESCE(pg_get_expr(p.polqual, p.polrelid), '')
         || COALESCE(pg_get_expr(p.polwithcheck, p.polrelid), '')) LIKE '%meeting-evidence%';
  IF v_bad IS NOT NULL THEN
    RAISE EXCEPTION 'a storage policy would let meeting evidence be replaced: %', v_bad;
  END IF;

  IF pg_get_functiondef('public.add_meeting_order_evidence(uuid,text,text)'::regprocedure)
     NOT LIKE '%assert_meeting_editor%' THEN
    RAISE EXCEPTION 'add_meeting_order_evidence does not authorize the caller';
  END IF;

  IF pg_get_functiondef('public.remove_meeting_order(uuid)'::regprocedure)
     NOT LIKE '%MEETING_ORDER_HAS_EVIDENCE%' THEN
    RAISE EXCEPTION 'remove_meeting_order does not refuse an order with evidence';
  END IF;

  IF has_function_privilege('anon', 'public.add_meeting_order_evidence(uuid,text,text)', 'EXECUTE') THEN
    RAISE EXCEPTION 'anon can execute add_meeting_order_evidence';
  END IF;
END $$;
